compile:
	g++ -c Subpopulation_Framework.cpp Classic_Subpopulation.cpp GDE3_Subpopulation.cpp Novelty_Subpopulation.cpp Subpopulation.cpp

#all:
	#g++ -Wall -g -o o main.cpp Ripple.cpp Differential_Evolution.cpp -lzrandom
#	g++ -Wall -g -o o main.cpp ../problems/WFG_Problem.cpp ../problems/Toolkit/* Subpopulation_Framework.cpp Subpopulation.cpp Classic_Subpopulation.cpp GDE3_Subpopulation.cpp Novelty_Subpopulation.cpp -lzrandom

all:
	#g++ -Wall -g -o o main.cpp Ripple.cpp Differential_Evolution.cpp -lzrandom
	g++ -Wall -g -o o main.cpp ../problems/WFG_Problem.cpp ../problems/Toolkit/* Differential_Evolution.cpp Subpopulation.cpp Classic_Subpopulation.cpp GDE3_Subpopulation.cpp Novelty_Subpopulation.cpp -lzrandom


